app-title = TMDビューアー
feeds-tab = タイムライン
settings-tab = 設定
feeds-empty-text = ツィートがありません
feeds-twitter-link =
  .title = Twitterで開く
feeds-retweet-text = {$username} さんがリツイート
feeds-input-username =
  .placeholder = ユーザ名
feeds-input-keyword =
  .placeholder = キーワード検索
feeds-input-has-media-only = メディア有り
feeds-input-page =
  .placeholder = ページ数
  .aria-label = ページ数
feeds-input-next-page =
  .title = 次のページ
  .aria-label = 次のページ
feeds-input-previous-page =
  .title = 前のページ
  .aria-label = 前のページ
settings-input-set-data-dir =
  .placeholder = 新しいデータディレクトリ
settings-set-data-dir-button = 更新
settings-scan-button = スキャン
settings-generate-thumbnails-button = サムネイル生成
settings-clean-database-button = データベース消去
settings-server-state-button = サーバ情報
settings-dark-mode = ダークモード