app-title = TMD Viewer
feeds-tab = Feeds
settings-tab = Settings
feeds-empty-text = No tweets
feeds-twitter-link =
  .title = Open on Twitter
feeds-retweet-text = {$username} retweeted.
feeds-input-username =
  .placeholder = Username
feeds-input-keyword =
  .placeholder = Keyword
feeds-input-has-media-only = Media only
feeds-input-page =
  .placeholder = Page
  .aria-label = Page
feeds-input-next-page =
  .title = Next page
  .aria-label = Next page
feeds-input-previous-page =
  .title = Previous page
  .aria-label = Previous page
settings-input-set-data-dir =
  .placeholder = New data directory
settings-set-data-dir-button = Update
settings-scan-button = Scan
settings-generate-thumbnails-button = Generate thumbnails
settings-clean-database-button = Delete database
settings-server-state-button = Server state
settings-dark-mode = Dark mode